"""Single source of truth for the QA catalogue.

Every automated test is tagged with a case id from here via @pytest.mark.case.
build_report.py joins this catalogue with the recorded run results to produce
the Excel test-case document, so the spreadsheet cannot drift from the code.
"""

P0, P1, P2, P3 = "P0 - Blocker", "P1 - High", "P2 - Medium", "P3 - Low"
CRIT, MAJ, MIN = "Critical", "Major", "Minor"

CASES: list[dict] = [
    # -- UNIT -----------------------------------------------------------------
    dict(id="TC-U-001", layer="Unit", module="Evidence routing", priority=P0, severity=CRIT,
         title="diversify_evidence surfaces every evidence kind in the top-24",
         precondition="Evidence pool where one kind (citation) outnumbers the 24-item cap.",
         steps="1. Build a pool of 25 citations plus code/patent/clinical/policy items.\n2. Call diversify_evidence().\n3. Inspect kinds present in the first 24 items.",
         expected="All distinct kinds appear within the first 24 items; citations no longer monopolise the cap."),
    dict(id="TC-U-002", layer="Unit", module="Evidence routing", priority=P0, severity=CRIT,
         title="diversify_evidence is loss-less",
         precondition="Arbitrary evidence pool.",
         steps="1. Call diversify_evidence() on a mixed pool.\n2. Compare output length and membership to the input.",
         expected="Output holds exactly the same items as the input; reordered only, nothing dropped or duplicated."),
    dict(id="TC-U-003", layer="Unit", module="Evidence routing", priority=P2, severity=MIN,
         title="diversify_evidence handles empty and single-kind pools",
         precondition="Edge-case inputs.",
         steps="1. Call with an empty list.\n2. Call with a pool containing one kind only.",
         expected="Returns empty list and the original order respectively; no exception raised."),
    dict(id="TC-U-004", layer="Unit", module="Relevance filter", priority=P1, severity=MAJ,
         title="build_relevance_filter keeps topically-matching items",
         precondition="Paper title with distinctive terms.",
         steps="1. Build a filter for a known title.\n2. Evaluate an item sharing a distinctive term.",
         expected="Filter returns True for the sharing item."),
    dict(id="TC-U-005", layer="Unit", module="Relevance filter", priority=P1, severity=MAJ,
         title="build_relevance_filter rejects items with no shared term",
         precondition="Paper title with distinctive terms.",
         steps="1. Build a filter for a known title.\n2. Evaluate a wholly unrelated item.",
         expected="Filter returns False."),
    dict(id="TC-U-006", layer="Unit", module="Relevance filter", priority=P2, severity=MIN,
         title="build_relevance_filter is permissive when no distinctive terms exist",
         precondition="Title consisting only of generic stop-words.",
         steps="1. Build a filter from a generic title.\n2. Evaluate any item.",
         expected="Returns True (fail-open) rather than silently discarding all evidence."),
    dict(id="TC-U-007", layer="Unit", module="Evidence pool", priority=P1, severity=MAJ,
         title="dedupe_evidence removes duplicates by URL or title",
         precondition="Pool containing repeated items.",
         steps="1. Build a pool with duplicate URLs.\n2. Call dedupe_evidence().",
         expected="Only the first occurrence of each URL/title survives."),
    dict(id="TC-U-008", layer="Unit", module="Summary format", priority=P0, severity=CRIT,
         title="Composed summary is capped at 150 words",
         precondition="Word-cap trim helper available.",
         steps="1. Feed an over-length paragraph to the trim helper.\n2. Count words in the result.",
         expected="Result is 150 words or fewer and ends on a complete sentence."),
    dict(id="TC-U-009", layer="Unit", module="Summary format", priority=P1, severity=MAJ,
         title="Banned puffery phrases are deflated",
         precondition="Deflate helper available.",
         steps="1. Pass text containing 'profound influence' or 'transformative'.\n2. Inspect the output.",
         expected="Banned marketing phrases are replaced with plain wording."),
    dict(id="TC-U-010", layer="Unit", module="Domain routing", priority=P1, severity=MAJ,
         title="plan_routing calls all sources when no domain is confidently detected",
         precondition="No profile fields supplied.",
         steps="1. Call plan_routing with empty fields and an ambiguous title.\n2. Inspect sources_called.",
         expected="Reason is no_clear_domain and every source in ALL_SOURCES is called."),
    dict(id="TC-U-011", layer="Unit", module="Domain routing", priority=P1, severity=MAJ,
         title="Patents are never skipped by domain routing",
         precondition="Any domain.",
         steps="1. Call plan_routing for several distinct domains.\n2. Assert patents is present each time.",
         expected="patents is always in sources_called because it is a CORE source."),

    # -- INTEGRATION ----------------------------------------------------------
    dict(id="TC-I-001", layer="Integration", module="Health", priority=P0, severity=CRIT,
         title="Backend /health responds 200 on localhost",
         precondition="uvicorn running on 127.0.0.1:8000.",
         steps="1. GET http://127.0.0.1:8000/health.",
         expected="200 with body {'status': 'ok'}."),
    dict(id="TC-I-002", layer="Integration", module="Health", priority=P0, severity=CRIT,
         title="Backend reachable through the public tunnel",
         precondition="ngrok tunnel running.",
         steps="1. GET the tunnel /health URL.",
         expected="200 - the backend URL baked into the frontend is reachable from the internet."),
    dict(id="TC-I-003", layer="Integration", module="Auth", priority=P0, severity=CRIT,
         title="Protected endpoints reject unauthenticated requests",
         precondition="No Authorization header.",
         steps="1. POST /api/analyze with no token.",
         expected="401 or 403, never 200. Protected data is not served anonymously."),
    dict(id="TC-I-004", layer="Integration", module="Auth", priority=P0, severity=CRIT,
         title="Protected endpoints reject a tampered JWT",
         precondition="A valid token with one character altered.",
         steps="1. POST /api/analyze with the tampered bearer token.",
         expected="401 or 403 - signature verification rejects the token."),
    dict(id="TC-I-005", layer="Integration", module="Auth", priority=P0, severity=CRIT,
         title="A validly-signed JWT is accepted",
         precondition="Token minted with create_orcid_token().",
         steps="1. GET /api/profile with the valid bearer token.",
         expected="Not 401/403 - the authentication path works end to end."),
    dict(id="TC-I-006", layer="Integration", module="Search", priority=P0, severity=CRIT,
         title="Paper search returns results for a known title",
         precondition="Backend up, OpenAlex reachable.",
         steps="1. GET /api/search with a known paper title.",
         expected="200 and at least one result carrying a title."),
    dict(id="TC-I-007", layer="Integration", module="Retrieval", priority=P0, severity=CRIT,
         title="Every evidence source is invoked by the retrieval pipeline",
         precondition="All external APIs reachable.",
         steps="1. Run retrieval_node for a real paper.\n2. Inspect routing_metadata.source_yield.",
         expected="source_yield reports a count for all nine sources; none missing from the report."),
    dict(id="TC-I-008", layer="Integration", module="Retrieval", priority=P0, severity=CRIT,
         title="Retrieval returns a diverse evidence mix, not citations only",
         precondition="A paper with GitHub, patent or policy signal.",
         steps="1. Run retrieval_node.\n2. Count distinct kinds in the first 24 evidence items.",
         expected="At least 4 distinct evidence kinds - regression guard for the citation-starvation bug."),
    dict(id="TC-I-009", layer="Integration", module="Retrieval", priority=P1, severity=MAJ,
         title="Sources returning nothing are reported, not silently hidden",
         precondition="At least one source returns zero items.",
         steps="1. Run retrieval_node.\n2. Inspect routing_metadata.sources_empty.",
         expected="sources_empty lists every source whose yield was zero, distinct from 'never called'."),
    dict(id="TC-I-010", layer="Integration", module="Fetchers", priority=P1, severity=MAJ,
         title="GitHub adoption fetcher executes without error",
         precondition="GitHub API reachable unauthenticated.",
         steps="1. Call fetch_github_adoption() for a real paper.",
         expected="Returns a list without raising; any items carry kind='code'."),
    dict(id="TC-I-011", layer="Integration", module="Fetchers", priority=P1, severity=MAJ,
         title="Patent fetcher executes without error",
         precondition="Patents endpoint reachable.",
         steps="1. Call fetch_google_patents() for a real paper.",
         expected="Returns a list without raising; any items carry kind='patent'."),
    dict(id="TC-I-012", layer="Integration", module="Fetchers", priority=P1, severity=MAJ,
         title="Downstream impact tracing classifies institutional adopters",
         precondition="A paper cited by company, government or healthcare institutions.",
         steps="1. Call fetch_downstream_impact().\n2. Inspect the kinds returned.",
         expected="Returns evidence; institutional adopters carry industry/policy/clinical_adoption kinds."),
    dict(id="TC-I-013", layer="Integration", module="Ops dashboard", priority=P1, severity=MAJ,
         title="Metrics API returns a well-formed snapshot",
         precondition="Backend up.",
         steps="1. GET /api/metrics.",
         expected="200 JSON containing uptime, rps, cache and error-rate keys plus health_status."),
    dict(id="TC-I-014", layer="Integration", module="Ops dashboard", priority=P1, severity=MAJ,
         title="Operations dashboard page renders",
         precondition="Backend up.",
         steps="1. GET /dashboard.",
         expected="200 HTML containing the dashboard markup."),
    dict(id="TC-I-015", layer="Integration", module="Error handling", priority=P1, severity=MAJ,
         title="Malformed request body is rejected cleanly",
         precondition="Valid token.",
         steps="1. POST /api/analyze with an invalid JSON schema.",
         expected="4xx validation error, never a 500 stack trace."),
    dict(id="TC-I-016", layer="Integration", module="Error handling", priority=P1, severity=MAJ,
         title="Empty search query is handled gracefully",
         precondition="Backend up.",
         steps="1. GET /api/search with an empty q parameter.",
         expected="A defined 2xx or 4xx response, not a 500."),
    dict(id="TC-I-017", layer="Integration", module="CORS", priority=P0, severity=CRIT,
         title="CORS preflight permits the deployed frontend origin",
         precondition="Backend up.",
         steps="1. Send OPTIONS /api/analyze with the pages.dev Origin and the X-LLM-Provider header.",
         expected="2xx with the origin echoed - the browser will not block the real call."),

    # -- FUNCTIONAL (Selenium) ------------------------------------------------
    dict(id="TC-F-001", layer="Functional", module="Landing page", priority=P0, severity=CRIT,
         title="Landing page loads with the correct title",
         precondition="Cloudflare Pages deployment live.",
         steps="1. Navigate to the site root in Edge.\n2. Read document.title.",
         expected="Page loads and the title contains 'REFlect AI'."),
    dict(id="TC-F-002", layer="Functional", module="Landing page", priority=P0, severity=CRIT,
         title="Primary value proposition is visible above the fold",
         precondition="Landing page loaded.",
         steps="1. Load the page.\n2. Assert the hero headline text is displayed.",
         expected="Hero copy about tracing research impact is rendered and visible."),
    dict(id="TC-F-003", layer="Functional", module="Auth entry", priority=P0, severity=CRIT,
         title="ORCID sign-in call to action is present and clickable",
         precondition="Landing page loaded.",
         steps="1. Locate the Sign in with ORCID control.\n2. Assert it is displayed and enabled.",
         expected="The demo entry point exists and is interactive."),
    dict(id="TC-F-004", layer="Functional", module="Auth entry", priority=P1, severity=MAJ,
         title="Sign-in modal opens on demand",
         precondition="Landing page loaded.",
         steps="1. Click the sign-in control.\n2. Wait for the modal.",
         expected="Modal appears containing ORCID sign-in guidance."),
    dict(id="TC-F-005", layer="Functional", module="Landing page", priority=P2, severity=MIN,
         title="Data-source credibility strip is rendered",
         precondition="Landing page loaded.",
         steps="1. Read page text.\n2. Assert known source names appear.",
         expected="OpenAlex, Semantic Scholar, Crossref and similar are listed."),
    dict(id="TC-F-006", layer="Functional", module="Client health", priority=P0, severity=CRIT,
         title="No uncaught JavaScript errors on load",
         precondition="Landing page loaded.",
         steps="1. Load the page.\n2. Read the browser log for SEVERE entries.",
         expected="No SEVERE JS console errors - nothing visibly broken during the demo."),
    dict(id="TC-F-007", layer="Functional", module="Ops dashboard", priority=P1, severity=MAJ,
         title="Operations dashboard renders its metric cards in a browser",
         precondition="Backend reachable.",
         steps="1. Navigate to /dashboard.\n2. Assert metric labels are present.",
         expected="Dashboard renders live metric cards and a health badge."),
    dict(id="TC-F-008", layer="Functional", module="Responsive", priority=P2, severity=MIN,
         title="Landing page is usable at mobile width",
         precondition="Landing page loaded.",
         steps="1. Resize the window to 390x844.\n2. Assert no horizontal overflow.",
         expected="Content reflows; document width does not exceed the viewport."),
    dict(id="TC-F-009", layer="Functional", module="Routing", priority=P2, severity=MIN,
         title="Unknown client route does not render a blank page",
         precondition="SPA deployed.",
         steps="1. Navigate to a nonsense path.\n2. Inspect rendered body text.",
         expected="The SPA renders something (redirect or fallback), not an empty document."),

    # -- NON-FUNCTIONAL -------------------------------------------------------
    dict(id="TC-N-001", layer="Non-functional", module="Performance", priority=P0, severity=CRIT,
         title="Health endpoint responds within 1s",
         precondition="Backend up.",
         steps="1. Time five sequential GET /health calls.\n2. Take the mean.",
         expected="Mean latency below 1000 ms - the service is responsive."),
    dict(id="TC-N-002", layer="Non-functional", module="Performance", priority=P1, severity=MAJ,
         title="Landing page loads within the demo budget",
         precondition="Site deployed.",
         steps="1. Measure browser navigation to fully loaded.",
         expected="Load completes in under 10 s on the demo network."),
    dict(id="TC-N-003", layer="Non-functional", module="Performance", priority=P1, severity=MAJ,
         title="Cache hit is materially faster than a cold miss",
         precondition="Cache helpers available.",
         steps="1. Populate the cache.\n2. Time a hit against the documented miss cost.",
         expected="A cache hit returns in single-digit milliseconds."),
    dict(id="TC-N-004", layer="Non-functional", module="Load", priority=P1, severity=MAJ,
         title="Backend stays healthy under concurrent requests",
         precondition="Backend up.",
         steps="1. Issue 20 concurrent GET /health calls.\n2. Count non-200 responses.",
         expected="All 20 return 200; no connection resets or timeouts."),
    dict(id="TC-N-005", layer="Non-functional", module="Security", priority=P0, severity=CRIT,
         title="Injection-style payloads are handled as inert data",
         precondition="Backend up.",
         steps="1. Submit SQL and NoSQL style payloads to the search endpoint.",
         expected="Treated as a literal string; no 500 and no evidence of execution."),
    dict(id="TC-N-006", layer="Non-functional", module="Security", priority=P1, severity=MAJ,
         title="Oversized input does not crash the service",
         precondition="Backend up.",
         steps="1. Submit a very large query string.\n2. Re-check /health afterwards.",
         expected="Bounded response and the service remains healthy."),
    dict(id="TC-N-007", layer="Non-functional", module="Security", priority=P1, severity=MAJ,
         title="Secrets are not exposed in API responses",
         precondition="Backend up.",
         steps="1. Fetch /health, /api/metrics and /dashboard.\n2. Scan bodies for key material.",
         expected="No API keys, client secrets or tokens appear in any response body."),
    dict(id="TC-N-008", layer="Non-functional", module="Resilience", priority=P1, severity=MAJ,
         title="Retrieval degrades gracefully when a source fails",
         precondition="At least one upstream source unavailable or rate-limited.",
         steps="1. Run retrieval with a failing source.\n2. Inspect the returned evidence.",
         expected="Pipeline still returns evidence from healthy sources; the failure is logged, not fatal."),
    dict(id="TC-N-009", layer="Non-functional", module="Availability", priority=P0, severity=CRIT,
         title="Backend process is supervised and auto-restarts",
         precondition="ReflectAI-Backend scheduled task configured.",
         steps="1. Query the scheduled task state.",
         expected="Task reports Running - the supervisor restarts uvicorn if it exits mid-demo."),
]

# Suite 2: adversarial security cases live in their own module for readability.
from testcases_security import SECURITY_CASES  # noqa: E402

CASES.extend(SECURITY_CASES)

BY_ID = {c["id"]: c for c in CASES}
